### ISSUE TITLE
Test coverage please.

### ISSUE THREAD

**Issue by smn** [praekeltfoundation/oneplus#133]
It's friday afternoon & @jonathanendersby and myself have been cowboy patching some issues that should've been caught by unit tests & code reviews.

Please make an effort to up the test-coverage, fix this currently feels a bit like this:

![git](https://cloud.githubusercontent.com/assets/1065/3934226/f7fbe976-2488-11e4-97a6-0aaba445387f.gif)

**Comment by smn** [comment]
The issue was the following:

```
>>> from bs4 import BeautifulSoup, NavigableString
>>>
>>> value = '<img src="/media/django-summernote/2014-07-30/f6ec4f0e-8833-4759-943a-397780b54b34.jpeg" style="vertical-align:middle"/>'
>>> soup = BeautifulSoup(value)
>>> soup.findAll(True)
[<img src="/media/django-summernote/2014-07-30/f6ec4f0e-8833-4759-943a-397780b54b34.jpeg" style="vertical-align:middle"/>]
>>> soup2 = BeautifulSoup(soup)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sdehaan/Documents/Repositories/go/ve/lib/python2.7/site-packages/bs4/__init__.py", line 161, in __init__
    markup = markup.read()
TypeError: 'NoneType' object is not callable
>>>
```

Somewhere you are chaining template tags, one of them is expecting a `BeautifulSoup` object but is given at times a string and at times a `soup` object. 

The issue found in production was: http://prd-sentry.za.prk-host.net/oneplus/oneplus-production/group/43210/, when initially fixed by calling `BeautifulSoup()` on value resulted in http://prd-sentry.za.prk-host.net/oneplus/oneplus-qa/group/43219/. Now what we're doing is:

```
soup = BeautifulSoup(unicode(value))
```

So that when given a soup object, we turn it into unicode and then parse it again with BS.

**Comment by jaderabbit** [comment]
The filter's shouldn't be returning beautiful soup objects at all! Which is why this appeared.
 I agree that this would have been picked up by testing and proper review. I'll admit that I'm still figuring out how best to do reviews. Sorry about that and thanks for the fix.
